### ISSUE TITLE
what command execute to see the preview?

### ISSUE THREAD

**Issue by gustavomc** [aki77/atom-source-preview-jade#6]
what command execute to see the preview

**Comment by israelfaria** [comment]
By default theres no keymap to this command. You need to open command pallete (ctrl + shift + p) and find Source Preview

**Comment by israelfaria** [comment]
I'm currently unable to either open it with coffee nor pug files. Not sure why it doesnt work.

**Comment by wtimme** [comment]
> I'm currently not being able to either open it with coffee nor pug files opened.

I have the exact same issue.

### Steps to reproduce
1. Open a pug file
2. Invoke the command interface (`cmd` + `shift` + `p` on macOS)
3. Locate and execute the _Source Preview: Toggle_ command

#### Expected behaviour
A pane displaying a preview of the resulting HTML source code should be toggled.

#### Observed behaviour
Nothing happens.

### Setup
- **source-preview:** 0.5.2
- **source-preview-pug:** 0.2.0
- **Atom:** Atom Beta (1.22.0-beta0)
- **OS:** macOS Sierra (10.12.6 (16G29))

**Comment by aki77** [comment]
Please try source-preview 0.5.3.

**Comment by wtimme** [comment]
Thanks, works like a charm!
